// next
import Head from 'next/head';

// react
import React from 'react';

interface LayoutProps {
	children: React.ReactNode;
}

const Layout = ({ children }: LayoutProps) => (
	<div className='layout-wrapper'>
		<Head>
			<meta name='description' content='Generated by create next app!! :D' />
			<link rel='icon' href='/favicon.ico' />
			<title>Vancouver Shop Local</title>
		</Head>

		<nav>Nav will go here!</nav>

		<main>{children}</main>

		<footer>Footer will go here!</footer>
	</div>
);

export default Layout;

// <Image src='/images/vercel.svg' alt='Vercel Logo' width={72} height={16} />
