import Head from 'next/head';
import type { ReactNode } from 'react';

// components
import Footer from '../Footer/Footer';
import Nav from '../Nav/Nav';

// styled components
import * as S from './Layout.styles';

// props type
type LayoutProps = {
  children: ReactNode;
};

const Layout = ({ children }: LayoutProps) => (
  <S.Wrapper>
    <Head>
      <meta name='description' content='Generated by create next app!! :D' />
      <link rel='icon' href='/favicon.ico' />
      <title>Vancouver Shop Local</title>
    </Head>

    <Nav />

    <main>{children}</main>

    <Footer />
  </S.Wrapper>
);

export default Layout;
